export interface Coordinate {
  X: number;
  Y: number;
  Z: number;
}

export interface LoadedMonsterData {
  dayTimeLocations: {
    locations: Coordinate[];
    Radius: number;
  };
  nightTimeLocations: {
    locations: Coordinate[];
    Radius: number;
  };
}

export const monsterDataMapping = {
  BOSS_JetDragon: require("./BOSS_JetDragon.json") as LoadedMonsterData,
  FlowerDinosaur_Electric:
    require("./FlowerDinosaur_Electric.json") as LoadedMonsterData,
  BOSS_LilyQueen_Dark:
    require("./BOSS_LilyQueen_Dark.json") as LoadedMonsterData,
  BOSS_KingAlpaca: require("./BOSS_KingAlpaca.json") as LoadedMonsterData,
  WizardOwl: require("./WizardOwl.json") as LoadedMonsterData,
  NightFox: require("./NightFox.json") as LoadedMonsterData,
  HadesBird: require("./HadesBird.json") as LoadedMonsterData,
  BOSS_BlackMetalDragon:
    require("./BOSS_BlackMetalDragon.json") as LoadedMonsterData,
  Baphomet: require("./Baphomet.json") as LoadedMonsterData,
  IceDeer: require("./IceDeer.json") as LoadedMonsterData,
  Deer_Ground: require("./Deer_Ground.json") as LoadedMonsterData,
  BOSS_FengyunDeeper: require("./BOSS_FengyunDeeper.json") as LoadedMonsterData,
  ChickenPal: require("./ChickenPal.json") as LoadedMonsterData,
  CaptainPenguin: require("./CaptainPenguin.json") as LoadedMonsterData,
  BOSS_FlowerDinosaur_Electric:
    require("./BOSS_FlowerDinosaur_Electric.json") as LoadedMonsterData,
  RobinHood_Ground: require("./RobinHood_Ground.json") as LoadedMonsterData,
  ColorfulBird: require("./ColorfulBird.json") as LoadedMonsterData,
  Werewolf: require("./Werewolf.json") as LoadedMonsterData,
  BirdDragon: require("./BirdDragon.json") as LoadedMonsterData,
  RaijinDaughter: require("./RaijinDaughter.json") as LoadedMonsterData,
  SkyDragon: require("./SkyDragon.json") as LoadedMonsterData,
  BOSS_SakuraSaurus: require("./BOSS_SakuraSaurus.json") as LoadedMonsterData,
  FlowerDinosaur: require("./FlowerDinosaur.json") as LoadedMonsterData,
  ThunderBird: require("./ThunderBird.json") as LoadedMonsterData,
  Horus: require("./Horus.json") as LoadedMonsterData,
  BOSS_NaughtyCat: require("./BOSS_NaughtyCat.json") as LoadedMonsterData,
  CowPal: require("./CowPal.json") as LoadedMonsterData,
  RobinHood: require("./RobinHood.json") as LoadedMonsterData,
  MopBaby: require("./MopBaby.json") as LoadedMonsterData,
  FoxMage: require("./FoxMage.json") as LoadedMonsterData,
  GrassPanda: require("./GrassPanda.json") as LoadedMonsterData,
  QueenBee: require("./QueenBee.json") as LoadedMonsterData,
  Serpent_Ground: require("./Serpent_Ground.json") as LoadedMonsterData,
  Penguin: require("./Penguin.json") as LoadedMonsterData,
  BOSS_BlueDragon: require("./BOSS_BlueDragon.json") as LoadedMonsterData,
  GrassMammoth: require("./GrassMammoth.json") as LoadedMonsterData,
  GrassRabbitMan: require("./GrassRabbitMan.json") as LoadedMonsterData,
  DreamDemon: require("./DreamDemon.json") as LoadedMonsterData,
  AmaterasuWolf: require("./AmaterasuWolf.json") as LoadedMonsterData,
  WhiteTiger: require("./WhiteTiger.json") as LoadedMonsterData,
  FlowerRabbit: require("./FlowerRabbit.json") as LoadedMonsterData,
  Kelpie: require("./Kelpie.json") as LoadedMonsterData,
  Yeti: require("./Yeti.json") as LoadedMonsterData,
  CuteButterfly: require("./CuteButterfly.json") as LoadedMonsterData,
  LizardMan_Fire: require("./LizardMan_Fire.json") as LoadedMonsterData,
  Hedgehog: require("./Hedgehog.json") as LoadedMonsterData,
  ElecPanda: require("./ElecPanda.json") as LoadedMonsterData,
  Alpaca: require("./Alpaca.json") as LoadedMonsterData,
  BOSS_Anubis: require("./BOSS_Anubis.json") as LoadedMonsterData,
  WoolFox: require("./WoolFox.json") as LoadedMonsterData,
  HerculesBeetle: require("./HerculesBeetle.json") as LoadedMonsterData,
  SakuraSaurus: require("./SakuraSaurus.json") as LoadedMonsterData,
  BlackMetalDragon: require("./BlackMetalDragon.json") as LoadedMonsterData,
  Manticore_Dark: require("./Manticore_Dark.json") as LoadedMonsterData,
  CuteMole: require("./CuteMole.json") as LoadedMonsterData,
  BOSS_ThunderBird: require("./BOSS_ThunderBird.json") as LoadedMonsterData,
  SheepBall: require("./SheepBall.json") as LoadedMonsterData,
  IceFox: require("./IceFox.json") as LoadedMonsterData,
  Ronin: require("./Ronin.json") as LoadedMonsterData,
  CuteFox: require("./CuteFox.json") as LoadedMonsterData,
  BOSS_KingAlpaca_Ice:
    require("./BOSS_KingAlpaca_Ice.json") as LoadedMonsterData,
  Yeti_Grass: require("./Yeti_Grass.json") as LoadedMonsterData,
  Umihebi_Fire: require("./Umihebi_Fire.json") as LoadedMonsterData,
  HawkBird: require("./HawkBird.json") as LoadedMonsterData,
  BOSS_PlantSlime: require("./BOSS_PlantSlime.json") as LoadedMonsterData,
  Deer: require("./Deer.json") as LoadedMonsterData,
  BlackGriffon: require("./BlackGriffon.json") as LoadedMonsterData,
  Kitsunebi: require("./Kitsunebi.json") as LoadedMonsterData,
  FlowerDoll: require("./FlowerDoll.json") as LoadedMonsterData,
  DarkCrow: require("./DarkCrow.json") as LoadedMonsterData,
  BOSS_GrassMammoth: require("./BOSS_GrassMammoth.json") as LoadedMonsterData,
  DrillGame: require("./DrillGame.json") as LoadedMonsterData,
  VioletFairy: require("./VioletFairy.json") as LoadedMonsterData,
  FlameBambi: require("./FlameBambi.json") as LoadedMonsterData,
  Kelpie_Fire: require("./Kelpie_Fire.json") as LoadedMonsterData,
  LizardMan: require("./LizardMan.json") as LoadedMonsterData,
  RedArmorBird: require("./RedArmorBird.json") as LoadedMonsterData,
  BOSS_Suzaku: require("./BOSS_Suzaku.json") as LoadedMonsterData,
  Monkey: require("./Monkey.json") as LoadedMonsterData,
  BOSS_WeaselDragon: require("./BOSS_WeaselDragon.json") as LoadedMonsterData,
  ElecCat: require("./ElecCat.json") as LoadedMonsterData,
  BerryGoat: require("./BerryGoat.json") as LoadedMonsterData,
  GhostBeast: require("./GhostBeast.json") as LoadedMonsterData,
  Baphomet_Dark: require("./Baphomet_Dark.json") as LoadedMonsterData,
  FireKirin_Dark: require("./FireKirin_Dark.json") as LoadedMonsterData,
  Ganesha: require("./Ganesha.json") as LoadedMonsterData,
  DarkScorpion: require("./DarkScorpion.json") as LoadedMonsterData,
  Manticore: require("./Manticore.json") as LoadedMonsterData,
  LilyQueen: require("./LilyQueen.json") as LoadedMonsterData,
  FlyingManta: require("./FlyingManta.json") as LoadedMonsterData,
  PinkCat: require("./PinkCat.json") as LoadedMonsterData,
  KingAlpaca: require("./KingAlpaca.json") as LoadedMonsterData,
  FlameBuffalo: require("./FlameBuffalo.json") as LoadedMonsterData,
  Boar: require("./Boar.json") as LoadedMonsterData,
  BOSS_QueenBee: require("./BOSS_QueenBee.json") as LoadedMonsterData,
  ThunderDog: require("./ThunderDog.json") as LoadedMonsterData,
  BlueDragon: require("./BlueDragon.json") as LoadedMonsterData,
  Eagle: require("./Eagle.json") as LoadedMonsterData,
  BOSS_SakuraSaurus_Water:
    require("./BOSS_SakuraSaurus_Water.json") as LoadedMonsterData,
  SweetsSheep: require("./SweetsSheep.json") as LoadedMonsterData,
  BOSS_GrassPanda_Electric:
    require("./BOSS_GrassPanda_Electric.json") as LoadedMonsterData,
  BOSS_MopKing: require("./BOSS_MopKing.json") as LoadedMonsterData,
  CatMage: require("./CatMage.json") as LoadedMonsterData,
  FairyDragon: require("./FairyDragon.json") as LoadedMonsterData,
  SharkKid_Fire: require("./SharkKid_Fire.json") as LoadedMonsterData,
  BOSS_KingBahamut: require("./BOSS_KingBahamut.json") as LoadedMonsterData,
  NaughtyCat: require("./NaughtyCat.json") as LoadedMonsterData,
  PinkLizard: require("./PinkLizard.json") as LoadedMonsterData,
  BOSS_LazyCatfish: require("./BOSS_LazyCatfish.json") as LoadedMonsterData,
  LazyDragon: require("./LazyDragon.json") as LoadedMonsterData,
  BOSS_FairyDragon: require("./BOSS_FairyDragon.json") as LoadedMonsterData,
  KingBahamut: require("./KingBahamut.json") as LoadedMonsterData,
  ThunderDragonMan: require("./ThunderDragonMan.json") as LoadedMonsterData,
  BOSS_Umihebi: require("./BOSS_Umihebi.json") as LoadedMonsterData,
  CatBat: require("./CatBat.json") as LoadedMonsterData,
  VolcanicMonster: require("./VolcanicMonster.json") as LoadedMonsterData,
  BOSS_Kirin: require("./BOSS_Kirin.json") as LoadedMonsterData,
  WeaselDragon: require("./WeaselDragon.json") as LoadedMonsterData,
  LazyCatfish: require("./LazyCatfish.json") as LoadedMonsterData,
  BOSS_Yeti_Grass: require("./BOSS_Yeti_Grass.json") as LoadedMonsterData,
  Suzaku: require("./Suzaku.json") as LoadedMonsterData,
  BOSS_HawkBird: require("./BOSS_HawkBird.json") as LoadedMonsterData,
  Serpent: require("./Serpent.json") as LoadedMonsterData,
  Kirin: require("./Kirin.json") as LoadedMonsterData,
  WindChimes: require("./WindChimes.json") as LoadedMonsterData,
  Bastet_Ice: require("./Bastet_Ice.json") as LoadedMonsterData,
  NegativeKoala: require("./NegativeKoala.json") as LoadedMonsterData,
  BOSS_DarkScorpion: require("./BOSS_DarkScorpion.json") as LoadedMonsterData,
  MopKing: require("./MopKing.json") as LoadedMonsterData,
  FengyunDeeper: require("./FengyunDeeper.json") as LoadedMonsterData,
  Gorilla: require("./Gorilla.json") as LoadedMonsterData,
  BOSS_SaintCentaur: require("./BOSS_SaintCentaur.json") as LoadedMonsterData,
  Carbunclo: require("./Carbunclo.json") as LoadedMonsterData,
  BluePlatypus: require("./BluePlatypus.json") as LoadedMonsterData,
  SharkKid: require("./SharkKid.json") as LoadedMonsterData,
  BirdDragon_Ice: require("./BirdDragon_Ice.json") as LoadedMonsterData,
  Garm: require("./Garm.json") as LoadedMonsterData,
  SoldierBee: require("./SoldierBee.json") as LoadedMonsterData,
  WindChimes_Ice: require("./WindChimes_Ice.json") as LoadedMonsterData,
  GrassMammoth_Ice: require("./GrassMammoth_Ice.json") as LoadedMonsterData,
  PinkRabbit: require("./PinkRabbit.json") as LoadedMonsterData,
  LittleBriarRose: require("./LittleBriarRose.json") as LoadedMonsterData,
  PlantSlime_Flower: require("./PlantSlime_Flower.json") as LoadedMonsterData,
  FireKirin: require("./FireKirin.json") as LoadedMonsterData,
  LavaGirl: require("./LavaGirl.json") as LoadedMonsterData,
  PlantSlime: require("./PlantSlime.json") as LoadedMonsterData,
  BOSS_IceHorse: require("./BOSS_IceHorse.json") as LoadedMonsterData,
  BOSS_BlackCentaur: require("./BOSS_BlackCentaur.json") as LoadedMonsterData,
  WhiteMoth: require("./WhiteMoth.json") as LoadedMonsterData,
};
